USE TEST;

DROP TRIGGER IF EXISTS INSERT_MEMBER;

DELIMITER //
CREATE TRIGGER INSERT_MEMBER AFTER INSERT ON MEMBER
FOR EACH ROW
BEGIN
	UPDATE DASH_BOARD
	SET
		DB_MEMBER = DB_MEMBER + 1;
END//
DELIMITER ;

INSERT INTO MEMBER(ME_ID, ME_PW) VALUES('ABC123','ABC123'),('ADMIN','ADMIN');

DROP TRIGGER IF EXISTS INSERT_BOARD;

DELIMITER //
CREATE TRIGGER INSERT_BOARD AFTER INSERT ON BOARD
FOR EACH ROW
BEGIN
	UPDATE MEMBER
	SET
		ME_BOARD_COUNT = ME_BOARD_COUNT + 1
	WHERE
		ME_ID = NEW.BO_ME_ID;
END//
DELIMITER ;

INSERT INTO BOARD(BO_TITLE, BO_ME_ID) VALUES('게시글', 'ABC123');

DROP TRIGGER IF EXISTS DELETE_BOARD;

DELIMITER //
CREATE TRIGGER DELETE_BOARD AFTER DELETE ON BOARD
FOR EACH ROW
BEGIN
	UPDATE MEMBER
	SET
		ME_BOARD_COUNT = ME_BOARD_COUNT - 1
	WHERE
		ME_ID = OLD.BO_ME_ID;
END//
DELIMITER ;

DELETE FROM BOARD WHERE BO_NUM = 1;

USE SHOPPINGMALL;

DROP TRIGGER IF EXISTS INSERT_ORDER_LIST;

DELIMITER //
CREATE TRIGGER INSERT_ORDER_LIST AFTER INSERT ON ORDER_LIST
FOR EACH ROW
BEGIN
	UPDATE `OPTION`
    SET
		OP_AMOUNT = OP_AMOUNT - NEW.OL_AMOUNT
        WHERE OP_NUM = NEW.OL_OP_NUM;
END//
DELIMITER ;

INSERT INTO
`ORDER`(OR_NUM,OR_TOTAL,OR_PRICE,OR_USE_POINT,OR_SAVE_POINT,OR_ME_ID,OR_AD_NUM)
VALUES(3,45000,45000,0,4500,'qwe123',2);
INSERT INTO ORDER_LIST(OL_AMOUNT,OL_PRICE,OL_OR_NUM,OL_OP_NUM)
VALUES(1,15000,3,1),(1,30000,3,3);

DROP TRIGGER IF EXISTS UPDATE_ORDER;

DELIMITER //
CREATE TRIGGER UPDATE_ORDER AFTER UPDATE ON `ORDER`
FOR EACH ROW
BEGIN
	IF NEW.OR_STATE = '구매확정' THEN
		UPDATE MEMBER
        SET
			ME_POINT = ME_POINT + NEW.OR_SAVE_POINT
		WHERE
			ME_ID = NEW.OR_ME_ID;
    END IF;
END//
DELIMITER ;

UPDATE `ORDER` SET OR_STATE = '구매확정' WHERE OR_NUM = 3;






